### ISSUE TITLE
Hide rows filter works same like Display filter.

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/aggregate#217]
#### Software and hardware versions 
GAE and Tomcat Aggregate v1.5.x, Java v1.8.x, ...

#### Problem description
Hide rows filter works in the same way as a Display filter.

#### Steps to reproduce the problem
Try to use Hide filter and Display filter with the same example - compare the results.

#### Expected behavior
Hide should really hide submissions which you do not want to display ;)

**Comment by mmarciniak90** [comment]
![a4](https://user-images.githubusercontent.com/3907554/41710966-79148b88-7536-11e8-9462-f4d36f412588.png)
![a5](https://user-images.githubusercontent.com/3907554/41710971-7bf15bba-7536-11e8-993b-89168cd5bf96.png)

**Comment by mmarciniak90** [comment]
@opendatakit-bot label "good first issue"
