### ISSUE TITLE
Improve error message when user attempts to upload form version that sorts before existing version

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/aggregate#244]
#### Software and hardware versions 
Aggregate v1.4.x, Java v1.8.171, GAE, ...

#### Problem description
Only first number of version number is considered when uploading form version, it enables you to add version 7 after version 60 but disables you to add version 500.  

#### Steps to reproduce the problem
1. Add to Aggregate form with version 2.
2. Add to Aggregate form with version 10.

"10" is greater than "2" but it is considered as "1" 

#### Expected behavior
Whole version number should be considered when uploading updated form version, not just the first one.

**Comment by lognaturel** [comment]
I agree that this is not ideal behavior. What's going on is that versions are sorted [lexicographically](https://en.wikipedia.org/wiki/Lexicographical_order) rather than numerically. That's why the recommendation is to use a 10-digit string of numbers, preferably starting with the date (e.g. 2018052201). That will ensure that later versions are sorted after earlier ones.

Given that it has been this way for such a long time, I'm not sure it's something we should change now.

I'm curious -- when did you run into this problem?

**Comment by kkrawczyk123** [comment]
When I tried to update form version with some random number not just a next one - once aggregate accepted that and once he didn't and I didn't understand why. I was curious so I digged a bit deeper and realize that it might have been an issue.

**Comment by lognaturel** [comment]
Thanks, @kkrawczyk123 that makes sense! @yanokwa @ggalmazor @dcbriccetti any thoughts on how to address this or not? Certainly a better error message would help. 

Currently it's 
```
Error: Form Already Exists for this Namespace/Id attribute org.opendatakit.aggregate.exception.ODKFormAlreadyExistsException: Form version is not lexically greater than existing form version. Update the form version and resubmit.
```

I would change it to something like
```
Form versions are sorted alphabetically. For example, version 10 sorts before version 2 because the left-most character is used to sort. Please update the form version and resubmit.

We recommend using 10-digit version numbers that use the current date and a count. For example, for the second form on May 5th, 2024, use 2018050502
````

**Comment by yanokwa** [comment]
I like this message! 

Related, could we also update the not so friendly message when you get when you upload an XLS form?

**Comment by yanokwa** [comment]
Improving the error message would be a good first start.

The only other option is what other ODK-compatible servers do, replace the old form with a new form and serve the new form.

**Comment by trustbirungi** [comment]
@getodk-bot claim
