### ISSUE TITLE
Weird html displayed as default content of text_widgets ex_printer_widget

### ISSUE THREAD

**Issue by kkrawczyk123** [getodk/aggregate#278]
#### Software and hardware versions 
Aggregate v1.6.x, GAE and Tomcat both

#### Problem description
Weird html displayed as default content of text_widgets ex_printer_widget, screenshot attached:
![screenshot from 2018-07-05 14-21-33](https://user-images.githubusercontent.com/33342488/42323093-37a9b964-805f-11e8-808e-a156f8394395.png)

#### Steps to reproduce the problem
1. Send submission of All widgets form to aggregate

#### Expected behavior
html should not be visible as submissions content

cc @ggalmazor

**Comment by ggalmazor** [comment]
I think this is not an issue introduced on this release and I don't think we should unescape the contents of this field because that would make Aggregate insecure.
