### ISSUE TITLE
ODK-Aggregate-v1.7.4-Windows.exe.zip contains no windows code

### ISSUE THREAD

**Issue by ehbossa** [getodk/aggregate#483]
#### Software and hardware versions 
Windows 10, Aggregate v1.7.4

#### Problem description
The file:
https://github.com/opendatakit/aggregate/releases/download/v1.7.4/ODK-Aggregate-v1.7.4-Windows.exe.zip

Contains: ODK-Aggregate-v1.7.4-**Linux-x64.run.zip**

#### Steps to reproduce the problem
Goto https://github.com/opendatakit/aggregate/releases/tag/v1.7.4
Download ODK-Aggregate-v1.7.4-Windows.exe.zip
Unzip Download ODK-Aggregate-v1.7.4-Windows.exe.zip
Verify that the file inside is: ODK-Aggregate-v1.7.4-**Linux-x64.run.zip**

#### Expected behavior
Similar to:
https://github.com/opendatakit/aggregate/releases/download/v1.7.3/ODK-Aggregate-v1.7.3-Windows.exe.zip

That contains: ODK Aggregate-v1.7.3-**Windows.exe**

#### Other information 
ODK-Aggregate-v1.7.4-**Linux-x64.run.zip**
contains: ODK-Aggregate-v1.7.4-Linux-x64.run

**Comment by ggalmazor** [comment]
Hi, @ehbossa!

I've just updated the windows asset in the v1.7.4 release. Could you try it, please?
