### ISSUE TITLE
Can't upload my XML file on the aggregate server

### ISSUE THREAD

**Issue by jonasjen** [getodk/aggregate#490]
<!-- I have been trying to upload an XML file on the aggregate server but i keep getting this error message
 Error: Problem with JavaRosa Parsing Form: org.opendatakit.aggregate.exception.ODKIncompleteSubmissionData: Javarosa failed to construct a FormDef. Is this an XForm definition?
Previously I have been able to upload it without any problem. Please help i don't know what to do plus I'm not too knowledgeable in using odk. Thanks.

**Comment by lognaturel** [comment]
Sorry to hear you're having trouble with your form on Aggregate, @jonasjen. Can you please file a support request at https://forum.getodk.org/c/support/6 with as much detail as possible? If you can attach your form definition you are most likely to get a helpful answer.
