### ISSUE TITLE
Exporting an Xml form

### ISSUE THREAD

**Issue by IDAKWOVICTOR** [getodk/aggregate#493]
#### Software and hardware versions
Windows/Linux/macOS, Aggregate v1.x.x, Java vx.x.x, ...

#### Other information
Things you tried, stack traces, related issues, suggestions on how to fix it...

**Comment by IDAKWOVICTOR** [comment]
Why does the ODK Imports XML forms and does not have the ability of Exporting Submitted forms in Xml but KML, CSV and Json.
I am currently Working on Social Tenure Domain Model (STDM), it works easily with an XML form. my challenge is the In Ability to export Xml Submitted forms

**Comment by lognaturel** [comment]
Hi, @IDAKWOVICTOR! For usage questions, please post at https://forum.getodk.org/c/support/6.

Typically people want to get their data from Aggregate into an analysis platform so the export and sync options focus on making that easy. If you'd like to work with raw XML, your best option is likely to [pull submissions using Briefcase](https://docs.getodk.org/briefcase-using/#pulling-forms).

If this doesn't answer your question, please write a support post on the forum link above and describe exactly what problem you're trying to solve.
